services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    ports:
      - "9200:9200" # HTTP API port
      - "9300:9300" # Node-to-node communication port
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.ml.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
#      - ES_JAVA_OPTS=-Xms6g -Xmx6g
    deploy:
      resources:
        reservations:
          memory: 6G
        limits:
          memory: 6G
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

