apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: elastic-vector
# Adjust the type based on if your pull secret is docker or podman. See doco for details
type: kubernetes.io/podmanconfigjson
data:
  config.json:
