apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhaiis-runner
  namespace: elastic-vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhaiis-runner
  template:
    metadata:
      labels:
        app: rhaiis-runner
    spec:
      containers:
        - name: rhaiis
          image: registry.redhat.io/rhaiis/vllm-cpu-rhel9:3.0.0
          args:
            - "--model"
            - "RedHatAI/Llama-3.2-1B-Instruct-FP8"
            - "--device"
            - "cpu"
            - "--max-model-len"
            - "2048"
            - "--enforce-eager"
            - "--disable-custom-all-reduce"
            - "--trust-remote-code"
            - "--worker-cls"
            - "vllm.worker.cpu_worker.CPUWorker"
            - "--disable-async-output-proc"
            - "--disable-frontend-multiprocessing"
            # Removed --attention-backend TORCH_SDPA as it's not recognized
          ports:
            - containerPort: 8000
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HUGGING_FACE_TOKEN
            - name: HF_HUB_OFFLINE
              value: "0"
            - name: VLLM_NO_USAGE_STATS
              value: "1"
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
            - name: VLLM_DISABLE_ASYNC_OUTPUT_PROC
              value: "1"
            - name: VLLM_USE_V1
              value: "0"
            - name: VLLM_DISABLE_FRONTEND_MULTIPROCESSING
              value: "1"
            - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
              value: "1800"
            - name: VLLM_PLATFORM
              value: "cpu"
            - name: VLLM_ATTENTION_BACKEND
              value: "TORCH_SDPA"
          resources:
            requests:
              memory: "8Gi"
              cpu: "4"
            limits:
              memory: "16Gi"
              cpu: "8"
          volumeMounts:
            - name: cache-volume
              mountPath: /opt/app-root/src/.cache
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: rhaiis-runner-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi