apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhaiis-runner-pvc
  namespace: elastic-vector
  labels:
    app: rhaiis-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
