apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-documents-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  nfs:
    path: /tmp
    server: 172.17.0.2