apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-documents
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi
  volumeName: ai-documents-pv
